services:
  localdb:
    container_name: blogDB
    image: mysql:8.0
    ports:
      - 3309:3306
    environment:
      MYSQL_ROOT_PASSWORD: root12345678
      MYSQL_DATABASE: hanadb
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --log_bin_trust_function_creators=1
      - --default-time-zone=Asia/Seoul
      - --innodb_ft_min_token_size=2
      - --innodb_ft_server_stopword_table=testdb/StopWord
    volumes:
      - ./mysql:/var/lib/mysql

# 포트 번호 : 3309
# 루트 비밀번호 : root12345678 